### ISSUE TITLE
dbmgr automatically exits itself after some time with "mongodb" enabled

### ISSUE THREAD

**Issue by sekkit** [imgamer/kbengine#8]
[  INFO] [0x00001718] [2019-08-28 11:35:39,902] Components::removeComponentByChannel: dbmgr : 4002, Normal exit!
 WARNING baseappmgr-1 13061 5002  [2019-08-28 11:35:39 901] - TCPPacketReceiver::processPendingEvents(192.168.1.7:1845): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
   ERROR baseappmgr-1 13061 5002  [2019-08-28 11:35:39 903] - Components::removeComponentByChannel: dbmgr : 4002, Abnormal exit! TCPPacketReceiver::processRecv(): errno=10054

**Comment by imgamer** [comment]
Fixed at 5af18bbcfcf5b9b832e7008869c54c9164f74c0b

**Comment by imgamer** [comment]
fixed at : add35468db6b1899a1695c8a493be2ad5efb7e05
